config/routes.rb
Rails.application.routes.draw do
  root 'tienda#index'
  get '/terminos_y_condiciones', to: 'tienda#terminos_y_condiciones', as: :terminos
  get '/aviso_de_privacidad', to: 'tienda#aviso_de_privacidad', as: :aviso_de_privacidad
  get 'tienda/fancy', as: :fancy
  get 'tienda/generate_subscriber', as: :generate_subscriber
  post 'tienda/generate_subscriber'
  devise_for :users
  resources :products, path: 'admin/products'
  get 'admin/customers', to: 'customers#index',as: :customers
  get 'admin/orders', to: 'customers#orders', as: :orders
  get 'admin/order/:id', to: 'customers#order', as: :order
  get 'admin/customers/acount', to: 'customers#acount_information', as: :acount
  get 'admin/shipments', to: 'customers#shipments',as: :shipments
  get 'admin/shipment', to: 'customers#shipment', as: :shipment
  get 'admin/find_orders', to: 'customers#find_orders', as: :find_orders
  post 'admin/find_orders', to: 'customers#find_orders'
  get 'admin/import_products', to: 'products#import_products', as: :import_products
  post 'admin/import_products', to: 'products#import_products'
  get 'admin/today_orders', to: 'customers#today_orders', as: :today_orders
  get 'admin/montly_orders', to: 'customers#montly_orders', as: :montly_orders
  get 'admin/inprocess_orders', to: 'customers#inprocess_orders', as: :inprocess_orders
  get 'admin/finish_orders', to: 'customers#finish_orders', as: :finish_orders
  get 'admin/in_send_orders', to: 'customers#in_send_orders', as: :in_send_orders
  get 'admin/activate_order', to: 'customers#activate_order', as: :activate_order
  post 'admin/activate_order', to: 'customers#activate_order'
  get 'admin/send_order', to: 'customers#send_order', as: :send_order
  post 'admin/send_order', to: 'customers#send_order'
  get 'admin/finish_order', to: 'customers#finish_order', as: :finish_order
  post 'admin/finish_order', to: 'customers#finish_order'
  get 'admin/admins',to: 'admins#index', as: :admins
  get 'admin/admins/new',   to: 'admins#new', as: :new_admin
  get 'admin/admins/create',   to: 'admins#create', as: :create
  post 'admin/admins/create',   to: 'admins#create'
  get 'admin/admins/edit',  to: 'admins#edit', as: :edit_admin
  get 'admin/admins/destroy',  to: 'admins#destroy', as: :destroy_admin
  get 'admin/admins/update_admin', to: 'admins#update_admin', as: :update_admin
  post 'admin/admins/update_admin', to: 'admins#update_admin'
  get 'admin/login', to: "admins#login_admin", as: :login
  get 'admin', to: "admins#admin", as: :admin_i
  get 'admin/admins/verify_pass', to: "admins#verify_pass", as: :verify_pass
  post 'admin/admins/verify_pass', to: "admins#verify_pass"
  get 'admin/admins/log_out', to: "admins#log_out", as: :log_out
  get 'all_items', to: 'tienda#productos', as: :all_items
  get 'search', to: 'tienda#search', as: :search
  get 'item-in-stock/:id', to: 'tienda#producto', as: :item
  get 'tienda/carrito'
  get 'tienda/confirmacion_pago', as: :confirmacion_pago
  get 'tienda/lista_de_productos', as: :lista_de_productos
  get 'tienda/actualizar_carrito', as: :actualizar_carrito
  get 'tienda/eliminar_items_del_carrito', as: :eliminar_items_del_carrito
  get 'tienda/crear_pedido', as: :crear_pedido
  post 'tienda/crear_pedido' 
  get 'tienda/buscar_pedido', as: :buscar_pedido
  post 'tienda/buscar_pedido'
  get 'tienda/ver_pedido', as: :ver_pedido
  post 'tienda/ver_pedido'
  get 'tienda/producto_no_encontrado', as: :producto_no_encontrado
  post 'tienda/producto_no_encontrado'
  get 'tienda/contacto', as: :contacto
  post 'tienda/contacto'
  get 'tienda/contactado', as: :contactado
  post 'tienda/contactado'
  get 'tienda/eliminar_item', as: :eliminar_item
  get 'tienda/offers', as: :offers
  get 'nosotros', to: 'tienda#nosotros', as: :about_us
  get 'admin/products/:id/products_photos',to: 'products#products_photos', as: :gallery
  get 'admin/products/:id/add_photos',to: 'products#add_photos', as: :add_photos
  post 'admin/products/:id/add_photos',to: 'products#add_photos'
  get 'admin/productos_no_publicados',to: 'products#productos_no_publicados', as: :productos_no_publicados
  post 'admin/productos_no_publicados',to: 'products#productos_no_publicados'
  get 'admin/eliminar_todos_los_productos_sin_publicar',to: 'products#eliminar_todos_los_productos_sin_publicar', as: :eliminar_todos_los_productos_sin_publicar
  post 'admin/eliminar_todos_los_productos_sin_publicar',to: 'products#eliminar_todos_los_productos_sin_publicar'
  get 'admin/destroy_photos/:id',to: 'products#destroy_photos', as: :destroy_photos
  post 'admin/destroy_photos/:id',to: 'products#destroy_photos'
  get 'admin/products/:id/activate_inactive',to: 'products#activate_inactive', as: :active_inactive
  post 'admin/products/:id/activate_inactive',to: 'products#activate_inactive'
  get 'admin/search_product', to: 'products#search_product', as: :search_product
  post 'admin/search_product', to: 'products#search_product' 
  get 'admin/active_all',to: 'products#active_all', as: :active_all
  post 'admin/active_all',to: 'products#active_all'
  get 'admin/unactive_all',to: 'products#unactive_all', as: :unactive_all
  post 'admin/unactive_all',to: 'products#unactive_all'
  get 'admin/products_import_list', to: 'products#import_list', as: :import_list
  get 'admin/categoria-de-producto', to: 'products#categoria', as: :categoria
  get 'admin/nueva_etiqueta',  to: 'tags_and_categories#nueva_etiqueta', as: :nueva_etiqueta 
  get 'payments/payment_proccess', as: :payment_proccess
  post 'payments/payment_proccess'
  get 'payments/tarjeta', as: :tarjeta
  post 'payments/tarjeta'
  get 'payments/oxxo', as: :oxxo
  post 'payments/oxxo'

  ######## api routes ########
  get 'api/list_products', :defaults => { :format => 'json' }
  get 'api/best_produtcs', :defaults => { :format => 'json' }
  get 'api/my_products', :defaults => { :format => 'json' }
  get 'api/categorias', :defaults => { :format => 'json' }
  post 'api/my_products', :defaults => { :format => 'json' }
  post 'api/image_products', :defaults => { :format => 'json' }
  get 'api/search', :defaults => { :format => 'json' }
  post 'api/favoritos', :defaults => { :format => 'json' }
  post 'api/generate_mobile_order', :defaults => { :format => 'json' }
  post 'api/tarjeta_pago_mobil', :defaults => { :format => 'json' }
  get 'api/find_order', :defaults => { :format => 'json' }



end

app/controllers/tienda_controller.rb
class TiendaController < ApplicationController
  before_filter :fancy_filter!, except: [:fancy, :generate_subscriber]
  layout 'single'

  def index
    @products_offer = Product.where("oferta > 0").where(publicado: true).limit(6)
    @products = Product.where(publicado: true).order("RANDOM()").limit(6)
    best_products = ProductosAPedido.limit(100).group(:product_id).order('count_all desc').count
    if best_products.nil?
      @best_products = []
    else
    i = 0
    ids = []
    best_products.each do |key,value|
      ids.push(key)
    end
    end

     @best_products = Product.where(id: ids) 
     render layout: "application"
  end

  
  def terminos_y_condiciones
  end

  def aviso_de_privacidad
  end
  
  def productos
    @products = Product.where(publicado: true).paginate(:page => params[:page], :per_page => 30).order('created_at DESC')
    best_products = ProductosAPedido.group(:product_id).order('count_all desc').count
    if best_products.nil?
      @best_products = []
    else
    i = 0
    array_p = []
    best_products.each do |key,value|
      @product = Product.find(key)
      puts @product.nombre
      array_p.push({
       product: @product,
       count: value
      })
      i = i + 1
      if i == 2
         @best_products = array_p
          puts "#{@best_products}"
        return false
      end
    end
    end
  end

  def offers
    @products = Product.where(publicado: true).where('oferta > 0').paginate(:page => params[:page], :per_page => 30).order('created_at DESC')
    best_products = ProductosAPedido.group(:product_id).order('count_all desc').count
    if best_products.nil?
      @best_products = []
    else
    i = 0
    array_p = []
    best_products.each do |key,value|
      @product = Product.find(key)
      puts @product.nombre
      array_p.push({
       product: @product,
       count: value
      })
      i = i + 1
      if i == 2
         @best_products = array_p
          puts "#{@best_products}"
        return false
      end
    end
    end
  end

  def nosotros
  end
  def search
    @products = Product.where(publicado: true)
    
    @products = @products.nombre(params[:search]) if params[:search].present?

    if @products.count == 0
    @products = Product.all
    @products = @products.categoria_principal_interna(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.nombre_cientifico(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.color1(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.color2(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.color3(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.color4(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.color5(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.pais_de_procedencia(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.familia(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.orden(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.region_climatica(params[:search]) if params[:search].present?
    end

    if @products.count == 0
    @products = Product.all
    @products = @products.luz(params[:search]) if params[:search].present?
    end
    
    if @products.count == 0
    @products = Product.all
    @products = @products.riego(params[:search]) if params[:search].present?
    end

    best_products = ProductosAPedido.group(:product_id).order('count_all desc').count
    if best_products.nil?
      @best_products = []
    else
    i = 0
    array_p = []
    best_products.each do |key,value|
      @product = Product.find(key)
      puts @product.nombre
      array_p.push({
       product: @product,
       count: value
      })
      i = i + 1
      if i == 2
         @best_products = array_p
          puts "#{@best_products}"
        return false
      end
    end
    end

  end

  def producto
    @product = Product.find(params[:id])

  end

  def carrito
  end

  def actualizar_carrito
    q = params[:cantidad].to_i
    q.times do 
      if session[:product] == nil 
        session[:product] = [params[:product]]
        session[:price] = params[:price]
        color = [] 
        color.push({"#{params[:product]}" =>params[:color]})
        session[:color] = session[:color].to_a + color 
      else
        session[:product] = session[:product] + [ params[:product] ]
        session[:price]   = session[:price].to_f + params[:price].to_f
        color = [] 
        color.push({"#{params[:product]}" =>params[:color]})
        session[:color] = session[:color].to_a + color 
      end
    end



    puts "#{session[:product]}"
    puts "#{session[:price]}"
    puts "#{session[:color]}"
    @q = q
    
    if session[:qdep].nil?
      session[:qdep] = 0
      session[:qdep] = session[:qdep] + @q
      else
      session[:qdep] = session[:qdep] + @q
    end

    session[:shipment_cost] = transport_cost(session[:qdep])

    puts ">>>>>>>>>>>>>>>>>>>>>>>>>> #{session[:qdep]}"
    puts ">>>>>>>>>>>>>>>>>>>>>>>>>> #{session[:shipment_cost]}"
    respond_to do |format|
      format.js
    end
  end

  def eliminar_items_del_carrito
      session[:product] = nil
      session[:price] = nil
      session[:color] = nil
      session[:pedido_final] = nil
      session[:line_items] = nil
      session[:productos_in_line] = nil
      session[:qdep] = nil
      session[:shipment_cost] = nil
       line_items_x = LineItem.find_by_session_token(session[:session_token])
       unless line_items_x.nil?
        line_items_x.destroy
       end

       productos_in_line_x = ProductosInLine.find_by_session_token(session[:session_token])
       unless productos_in_line_x.nil?
        productos_in_line_x.destroy
       end
      flash[:notice] = "Se han eliminado los items del carrito"
      redirect_to :back
  end

  def lista_de_productos
    require 'json'
    @products = session[:product]
    @total = session[:price]
    @colors = session[:color]
    unless @products.nil?
    products = @products.group_by{|x| x}.values
    products_docificate = []

    products.each do |p|
      px = Product.find(p[0].to_i)
      py = p.size

      products_docificate.push([px,py])
    end

    @products = products_docificate
    
    
    @pedido = []
     
     @colors.each do |c|
      c.map { |key, value|  @pedido.push(product_id: key, color: value, oferta: 0) }
     end
     productos_in_line = []
     line_items = []
     @products.each do |product|
       inject = product[0]
       colors = []
       img = inject.image_products.first.file.standar.url
       nombre = inject.nombre 
       id = inject.id
       unit_price = inject.precio_final
       unit_price_x = inject.precio_final * 100
       quantity = product[1].to_i
       order = ""
       total_product = inject.precio_final.round * product[1].to_i

       @colors.each do |color|
          if color["#{inject.id}"]
              colors.push(color["#{inject.id}"])
          end
       end
       my_colors = []
       colors.group_by{|x| x}.values.map.each do |mm|
         my_colors.push( "#{mm[0]} = #{mm.count}" )
       end

       puts "**************************** #{my_colors} colors"

       productos_in_line.push({
        id: id,
        img: img,
        nombre: nombre,
        unit_price: unit_price,
        my_colors:  my_colors,
        quantity: quantity,
        order: order,
        offer: 0,
        total_product: total_product

       })
       
       line_items.push({
        name: nombre,
        unit_price: unit_price_x.to_i,
        quantity: quantity
       })
    end

     session[:pedido_final] = @pedido


     line_items_x = LineItem.find_by_session_token(session[:session_token])
     unless line_items_x.nil?
      line_items_x.destroy
     end

     productos_in_line_x = ProductosInLine.find_by_session_token(session[:session_token])
     unless productos_in_line_x.nil?
      productos_in_line_x.destroy
     end

     line_items_x = LineItem.new
     line_items_x.session_token = session[:session_token]
     line_items_x.line_items = line_items
     line_items_x.save!

     session[:line_items] = line_items_x

     productos_in_line_x  = ProductosInLine.new
     productos_in_line_x.session_token = session[:session_token]
     productos_in_line_x.productos_in_line = productos_in_line
     productos_in_line_x.save!

     session[:productos_in_line] = productos_in_line_x
     puts "#{productos_in_line_x.productos_in_line}"
     @productos = eval(productos_in_line_x.productos_in_line)

     else
     session[:pedido_final] = nil
     session[:line_items] = nil
     session[:productos_in_line] = nil
     @productos = []

   end

  end

  def crear_pedido
    pedido_final = session[:pedido_final]
    productos_in_line_x = session[:productos_in_line]
    lista = eval(productos_in_line_x.productos_in_line)
    pdx = Pedido.find_by_session_token(session[:session_token])
    if pdx.nil?
    pedido = Pedido.new
    pedido.codigo = SecureRandom.hex(10)
    pedido.total = session[:price].to_i
    pedido.session_token =  session[:session_token]
    pedido.aceptacion_de_terminos = params[:conditions]
    pedido.metodo_de_envio = "Uber Garden"
    pedido.costo_de_envio = session[:shipment_cost].round()
     if current_user

app/helpers/tienda_helper.rb
module TiendaHelper
end

app/views/tienda/_boton_agregar_carrito.html.erb
<% unless mobile_device? %>
<% if product.oferta.nil? %>
<h3 style="color:#ea2840;"><b>$ <%= product.precio_final %> MXN </b></h3><br/><br/>
<%else%>
<%= image_tag 'oferta.png', width: '50%', style: 'position: relative;' %>
<h3><strike style="color: red;">$<%=product.precio%></strike> &#x2192; <b style="color:#D6CA27;"> $<%= product.precio_final %> MXN </b></h3>
<h4> Estas ahorrando $<%= product.descuento %> pesos. </h4>
<%end%>
<i>Opcciones</i><br/>
<% if product.color1 != ""  %>
<% if product.color1 != nil %>
<div id="p1" class="colorem btn btn-single btn-small bnt-active-green" style="margin-top:10px;" onclick="color_select('p1','<%= product.color1 %>')">
	<%= product.color1 %>
</div>
<%end%>
<%end%>
<% if product.color2 != "" %>
<% if product.color2 != nil %>
<div id="p2" class="colorem btn btn-single btn-small" style="margin-top:10px;" onclick="color_select('p2','<%= product.color2 %>')">
	<%= product.color2 %>
</div>
<%end%>
<%end%>
<% if product.color3 != "" %>
<% if product.color3 != nil %>
<div id="p3" class="colorem btn btn-single btn-small" style="margin-top:10px;" onclick="color_select('p3','<%= product.color3 %>')">
	<%= product.color3 %>
</div>
<%end%>
<%end%>
<% if product.color4 != "" %>
<% if product.color4 != nil %>
<div id="p4" class="colorem btn btn-single btn-small" style="margin-top:10px;" onclick="color_select('p4','<%= product.color4%>')">
	<%= product.color4 %>
</div>
<%end%>
<%end%>
<% if product.color5 != "" %>
<% if product.color5 != nil %>
<div id="p5" class="colorem btn btn-single btn-small" style="margin-top:10px;" onclick="color_select('p5','<%= product.color5 %>')">
	<%= product.color5 %>
</div>
<%end%>
<%end%>
<br/><br/>
<i>¡Estas listo!</i><br/>
<div class="col-md-4" style="margin-top: 20px;">
	<%= number_field_tag 'cantidad', 1, class: "form-control" %>
</div>
<div class="col-md-8" style="margin-top: 20px;">
	<h4>Cantidad</h4>
</div>
<div class="col-lg-12" style="margin-top: 20px;">
	<%= link_to actualizar_carrito_path(product: product.id, price: product.precio, color: product.color1, cantidad: 1), class: "btn btn-buy ", id: "carrito_link",remote: true do %>
	Comprar ahora <i class="fa fa-cart-plus" aria-hidden="true"></i>
	<%end%>
</div>
<%else%>
<div class="row">
	<% if product.oferta.nil? %>
	<div class="panel panel-default" style="background: rgba(13, 24, 20, 0.9);">
		<div class="row">
			<div class="col-lg-12">
				<center>
				<h3 style="color:#fff;">Precio:  <b style="color:#ea2840; "> $<%= product.precio_final %> MXN </b></h3><br/>
				</center>
			</div>
		</div>
	</div>
	<%else%>
	<div class="panel panel-default" style="background: rgba(13, 24, 20, 0.9);">
		<center>
		<h3><p style="color:#fff;"> De </p><strike style="color: red;"> $<%=product.precio%></strike><p style="color:#fff;"> a tan solo </p><b style="color:#fff;"> $<%= product.precio_final %> MXN </b></h3>
		<h4 style="color: #fff;"> Estas ahorrando $<%= product.descuento %> pesos. </h4>
		</center>
	</div>
	<%end%>
</div>
<i>Opcciones</i><br/>
<% if product.color1 != ""  %>
<% if product.color1 != nil %>
<div id="p1" class="colorem btn btn-single btn-small bnt-active-green" style="margin-top:10px;" onclick="color_select('p1','<%= product.color1 %>')">
	<%= product.color1 %>
</div>
<%end%>
<%end%>
<% if product.color2 != "" %>
<% if product.color2 != nil %>
<div id="p2" class="colorem btn btn-single btn-small" style="margin-top:10px;" onclick="color_select('p2','<%= product.color2 %>')">
	<%= product.color2 %>
</div>
<%end%>
<%end%>
<% if product.color3 != "" %>
<% if product.color3 != nil %>
<div id="p3" class="colorem btn btn-single btn-small" style="margin-top:10px;" onclick="color_select('p3','<%= product.color3 %>')">
	<%= product.color3 %>
</div>
<%end%>
<%end%>
<% if product.color4 != "" %>
<% if product.color4 != nil %>
<div id="p4" class="colorem btn btn-single btn-small" style="margin-top:10px;" onclick="color_select('p4','<%= product.color4%>')">
	<%= product.color4 %>
</div>
<%end%>
<%end%>
<% if product.color5 != "" %>
<% if product.color5 != nil %>
<div id="p5" class="colorem btn btn-single btn-small" style="margin-top:10px;" onclick="color_select('p5','<%= product.color5 %>')">
	<%= product.color5 %>
</div>
<%end%>
<%end%>
<br/><br/>
<i>¡Estas listo!</i><br/>
<div class="col-md-4" style="margin-top: 20px;">
	<%= number_field_tag 'cantidad', 1, class: "form-control" %>
</div>
<div class="col-md-8" style="margin-top: 20px;">
	<h4>Cantidad</h4>
</div>
<div class="col-lg-12" style="margin-top: 20px;">
	<%= link_to actualizar_carrito_path(product: product.id, price: product.precio, color: product.color1, cantidad: 1), class: "btn btn-buy ", id: "carrito_link",remote: true do %>
	Comprar ahora <i class="fa fa-cart-plus" aria-hidden="true"></i>
	<%end%>
</div>
<%end%>

app/views/tienda/actualizar_carrito.js.erb
$('#prodexp').html("<%= session[:product].size %>");
$('#pricexp').html("<%= (session[:price].to_f).round(2) %>");
//alert('Se han agregado <%= @q %> producto(s) al carrito');

app/views/tienda/aviso_de_privacidad.html.erb
<%= render partial: 'layout_parts/privacidad' %>

app/views/tienda/contactado.html.erb
<div class="row">
	<div class="col-lg-12">
		<%= render partial: '/layout_parts/left_menu', locals: {bp: @best_products} %>
		<div class="col-lg-9">
			<center>
			<h1> ¡ Gracias por contactarnos !</h1><br/>
			<%= link_to 'Ir a los productos', all_items_path %>
			</center>
		</div>
	</div>
</div>

app/views/tienda/index.html.erb
<div class="container">
	<% unless mobile_device? %>
	<div class="row">
		<div class="col-md-12" >
			<a href="<%= all_items_path %>">
				<%= image_tag('promo2/ubergarden.jpg', width: "100%") %>
			</a>
		</div>
	</div>
	<%end%>
	<br/>
	<div class="row">
		<div class="col-md-6">
			<% unless mobile_device? %>
			<a href="<%= search_path(search: 'Orquídea') %>">
				<%= image_tag('promo2/orquideas.jpg', width: "122%") %><br/><br/>
			</a>
			<a href="<%= search_path(search: 'flores') %>">
				<%= image_tag('promo2/flores.jpg', width: "122%") %>
			</a>
			<%end%>
		</div>
		<div class="col-md-1">
		</div>
		
		<div class="col-md-5">
			<a href="<%= search_path(search: 'Noche Buena') %>">
				<%= image_tag('promo2/destacado-nochebuena.jpg', width: "100%") %>
			</a>
		</div>
		
	</div>
	<br/>
	<% unless mobile_device? %>
	<div class="row">
		<div class="col-md-12" >
			<%= link_to offers_path do %>
			<%= image_tag('promo2/oferta.jpg', width: "100%") %>
			<%end%>
		</div>
	</div>
	<%end%>
	<% if mobile_device? %>
	<div class="row">
		<div class="col-md-12" >
			<a href="<%= all_items_path %>">
				<%= image_tag('promo2/ubergarden.jpg', width: "100%") %>
			</a>
		</div>
	</div>
	<%end%>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h3>Ofertas</h3>
				<% @products_offer.each do |product| %>
				<%= render partial: "/layout_parts/item_col_two", locals: {title: "#{product.nombre}", price: "#{product.precio}", descript: "#{product.descripccion}", img: product.image_products.last, product: product} %>
				<%end%>
			</div>
		</div>
	</div>
	<div class="row">
		<div clas="col-lg-12" style="width: auto;">
			<%= link_to search_path(search: 'macetas') do %>
			<%= image_tag('promo2/macetas.jpg', width: "100%") %>
			<%end%>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h3>Productos recomendados</h3>
				<% @products.each do |product| %>
				<%= render partial: "/layout_parts/item_col_two", locals: {title: "#{product.nombre}", price: "#{product.precio}", descript: "#{product.descripccion}", img: product.image_products.last, product: product} %>
				<%end%>
			</div>
		</div>
	</div>
	<div class="row">
		<div clas="col-lg-12" style="width: auto;">
			<%= link_to search_path(search: 'muebles') do %>
			<%= image_tag('promo2/muebles2.jpg', width: "100%") %>
			<%end%>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h3>Categorías</h3>
				<% $CATEGORIAS.each do |categoria| %>
				<a href="<%= search_path(search: categoria[:search]) %>" class="tagx" >
					<center>
					<h5><%= truncate(categoria[:name], length: 35, separator: ' ', omission: '...')%></h5>
					</center>
				</a>
				<%end%>
			</div>
			<div class="col-md-4">
				<div class="col-md-2">
					<div style="margin-top: 40px;">
						<%= image_tag('escudo.png', width: "50px") %>
					</div>
				</div>
				<div class="col-md-10">
					<h3>Protegemos tu compra</h3>
					<ul>
						<li>Paga en linea o en el OXXO.</li>
						<li>No conservamos datos bancarios.</li>
						<li>Tenemos nuestro propio servicio de entregas.</li>
						<li>Rastrea tu compra desde nuestra web.</li>
						<li>Envios solo en D.F. y area metropolitana.</li>
					</ul>
					<div class="col-lg-12 pull-right">
						<%= image_tag 'cards2.png', width: "40%" %>
						<%= image_tag 'oxxo.png', width: "20%" %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br/>
	<div class="row">
		<div class="col-md-12" >
			<%= link_to about_us_path do %>
			<%= image_tag('promo2/medioambiente.jpg', width: "100%") %>
			<%end%>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h3>Lo más vendido</h3>
				<% @best_products.each do |product| %>
				<%= render partial: "/layout_parts/item_col_two", locals: {title: "#{product.nombre}", price: "#{product.precio}", descript: "#{product.descripccion}", img: product.image_products.last, product: product} %>
				<%end%>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<% unless mobile_device? %>
			<%= link_to search_path(search: 'herramientas') do %>
			<%= image_tag('promo2/herramientas.jpg', width: "122%") %>
			<%end%>
			<br/><br/>
			<%= link_to search_path(search: 'tierra') do %>
			<%= image_tag('promo2/tierra.jpg', width: "122%") %>
			<%end%>
			<%end%>
		</div>
		<div class="col-md-1">
		</div>
		
		<div class="col-md-5" >
			<%= link_to terminos_path do %>
			<%= image_tag('terminos/terminos_verano.jpg', width: "100%", style:"border:solid 1px #BDBDBD;") %>
			<%end%>
		</div>
	</div>
	<br/><br/><br/>
</div>