config/routes.rb
Rails.application.routes.draw do
  root 'tienda#index'
  get '/terminos_y_condiciones', to: 'tienda#terminos_y_condiciones', as: :terminos
  get '/aviso_de_privacidad', to: 'tienda#aviso_de_privacidad', as: :aviso_de_privacidad
  get 'tienda/fancy', as: :fancy
  get 'tienda/generate_subscriber', as: :generate_subscriber
  post 'tienda/generate_subscriber'
  devise_for :users
  resources :products, path: 'admin/products'
  get 'admin/customers', to: 'customers#index',as: :customers
  get 'admin/orders', to: 'customers#orders', as: :orders
  get 'admin/order/:id', to: 'customers#order', as: :order
  get 'admin/customers/acount', to: 'customers#acount_information', as: :acount
  get 'admin/shipments', to: 'customers#shipments',as: :shipments
  get 'admin/shipment', to: 'customers#shipment', as: :shipment
  get 'admin/find_orders', to: 'customers#find_orders', as: :find_orders
  post 'admin/find_orders', to: 'customers#find_orders'
  get 'admin/import_products', to: 'products#import_products', as: :import_products
  post 'admin/import_products', to: 'products#import_products'
  get 'admin/today_orders', to: 'customers#today_orders', as: :today_orders
  get 'admin/montly_orders', to: 'customers#montly_orders', as: :montly_orders
  get 'admin/inprocess_orders', to: 'customers#inprocess_orders', as: :inprocess_orders
  get 'admin/finish_orders', to: 'customers#finish_orders', as: :finish_orders
  get 'admin/in_send_orders', to: 'customers#in_send_orders', as: :in_send_orders
  get 'admin/activate_order', to: 'customers#activate_order', as: :activate_order
  post 'admin/activate_order', to: 'customers#activate_order'
  get 'admin/send_order', to: 'customers#send_order', as: :send_order
  post 'admin/send_order', to: 'customers#send_order'
  get 'admin/finish_order', to: 'customers#finish_order', as: :finish_order
  post 'admin/finish_order', to: 'customers#finish_order'
  get 'admin/admins',to: 'admins#index', as: :admins
  get 'admin/admins/new',   to: 'admins#new', as: :new_admin
  get 'admin/admins/create',   to: 'admins#create', as: :create
  post 'admin/admins/create',   to: 'admins#create'
  get 'admin/admins/edit',  to: 'admins#edit', as: :edit_admin
  get 'admin/admins/destroy',  to: 'admins#destroy', as: :destroy_admin
  get 'admin/admins/update_admin', to: 'admins#update_admin', as: :update_admin
  post 'admin/admins/update_admin', to: 'admins#update_admin'
  get 'admin/login', to: "admins#login_admin", as: :login
  get 'admin', to: "admins#admin", as: :admin_i
  get 'admin/admins/verify_pass', to: "admins#verify_pass", as: :verify_pass
  post 'admin/admins/verify_pass', to: "admins#verify_pass"
  get 'admin/admins/log_out', to: "admins#log_out", as: :log_out
  get 'all_items', to: 'tienda#productos', as: :all_items
  get 'search', to: 'tienda#search', as: :search
  get 'item-in-stock/:id', to: 'tienda#producto', as: :item
  get 'tienda/carrito'
  get 'tienda/confirmacion_pago', as: :confirmacion_pago
  get 'tienda/lista_de_productos', as: :lista_de_productos
  get 'tienda/actualizar_carrito', as: :actualizar_carrito
  get 'tienda/eliminar_items_del_carrito', as: :eliminar_items_del_carrito
  get 'tienda/crear_pedido', as: :crear_pedido
  post 'tienda/crear_pedido' 
  get 'tienda/buscar_pedido', as: :buscar_pedido
  post 'tienda/buscar_pedido'
  get 'tienda/ver_pedido', as: :ver_pedido
  post 'tienda/ver_pedido'
  get 'tienda/producto_no_encontrado', as: :producto_no_encontrado
  post 'tienda/producto_no_encontrado'
  get 'tienda/contacto', as: :contacto
  post 'tienda/contacto'
  get 'tienda/contactado', as: :contactado
  post 'tienda/contactado'
  get 'tienda/eliminar_item', as: :eliminar_item
  get 'tienda/offers', as: :offers
  get 'nosotros', to: 'tienda#nosotros', as: :about_us
  get 'admin/products/:id/products_photos',to: 'products#products_photos', as: :gallery
  get 'admin/products/:id/add_photos',to: 'products#add_photos', as: :add_photos
  post 'admin/products/:id/add_photos',to: 'products#add_photos'
  get 'admin/productos_no_publicados',to: 'products#productos_no_publicados', as: :productos_no_publicados
  post 'admin/productos_no_publicados',to: 'products#productos_no_publicados'
  get 'admin/eliminar_todos_los_productos_sin_publicar',to: 'products#eliminar_todos_los_productos_sin_publicar', as: :eliminar_todos_los_productos_sin_publicar
  post 'admin/eliminar_todos_los_productos_sin_publicar',to: 'products#eliminar_todos_los_productos_sin_publicar'
  get 'admin/destroy_photos/:id',to: 'products#destroy_photos', as: :destroy_photos
  post 'admin/destroy_photos/:id',to: 'products#destroy_photos'
  get 'admin/products/:id/activate_inactive',to: 'products#activate_inactive', as: :active_inactive
  post 'admin/products/:id/activate_inactive',to: 'products#activate_inactive'
  get 'admin/search_product', to: 'products#search_product', as: :search_product
  post 'admin/search_product', to: 'products#search_product' 
  get 'admin/active_all',to: 'products#active_all', as: :active_all
  post 'admin/active_all',to: 'products#active_all'
  get 'admin/unactive_all',to: 'products#unactive_all', as: :unactive_all
  post 'admin/unactive_all',to: 'products#unactive_all'
  get 'admin/products_import_list', to: 'products#import_list', as: :import_list
  get 'admin/categoria-de-producto', to: 'products#categoria', as: :categoria
  get 'admin/nueva_etiqueta',  to: 'tags_and_categories#nueva_etiqueta', as: :nueva_etiqueta 
  get 'payments/payment_proccess', as: :payment_proccess
  post 'payments/payment_proccess'
  get 'payments/tarjeta', as: :tarjeta
  post 'payments/tarjeta'
  get 'payments/oxxo', as: :oxxo
  post 'payments/oxxo'

  ######## api routes ########
  get 'api/list_products', :defaults => { :format => 'json' }
  get 'api/best_produtcs', :defaults => { :format => 'json' }
  get 'api/my_products', :defaults => { :format => 'json' }
  get 'api/categorias', :defaults => { :format => 'json' }
  post 'api/my_products', :defaults => { :format => 'json' }
  post 'api/image_products', :defaults => { :format => 'json' }
  get 'api/search', :defaults => { :format => 'json' }
  post 'api/favoritos', :defaults => { :format => 'json' }
  post 'api/generate_mobile_order', :defaults => { :format => 'json' }
  post 'api/tarjeta_pago_mobil', :defaults => { :format => 'json' }
  get 'api/find_order', :defaults => { :format => 'json' }



end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  layout 'admin'
  before_filter :admin_filter

  def index
    @customers = CustomerRegister.paginate(:page => params[:page], :per_page => 20).order('created_at DESC')
  end

  def orders
   # @orders = Conekta::Order.where(:customer_info['customer_id'] => params[:customer])
   # puts @orders
   if params[:search]
    
    else
    if params[:customer] 
    @orders = Pedido.where(conekta_customer: params[:customer]).where("conekta_order <> ''").paginate(:page => params[:page], :per_page => 30).order('created_at DESC')
    else
    @orders = Pedido.where("conekta_order <> ''").paginate(:page => params[:page], :per_page => 20).order('created_at DESC')
    end
   end
  end

  def order
    @order = Pedido.find(params[:id])
  end

  def today_orders
    require 'csv'
    @orders = Pedido.where("conekta_order <> ''").where("created_at >= ?", Time.zone.now.beginning_of_day).paginate(:page => params[:page], :per_page => 30).order('created_at DESC')
    respond_to do |format|
      format.html
      format.csv { render text: @orders.to_csv }
    end
  end

  def montly_orders
    require 'csv'

    @orders = Pedido.this_month.where("conekta_order <> ''").paginate(:page => params[:page], :per_page => 30).order('created_at DESC')

    respond_to do |format|
      format.html
      format.csv { render text: @orders.to_csv }
    end
  end

  def inprocess_orders
    @orders = Pedido.where(activacion_de_pedido: true).paginate(:page => params[:page], :per_page => 30).order('created_at DESC')
  end

  def finish_orders
    @orders = Pedido.where(finalizacion_de_pedido: true).paginate(:page => params[:page], :per_page => 30).order('created_at DESC')
  end

  def in_send_orders
    @orders = Pedido.where(estatus_del_pedido: "En trayecto").paginate(:page => params[:page], :per_page => 30).order('created_at DESC')
  end

  def find_orders
    @order = Pedido.find_by_codigo(params[:search])

    if @order.nil?
      @order = Pedido.find_by_conekta_order(params[:search])
      if @order.nil?
        flash[:notice] = "No se ha encontrado el pedido que se busca"
        redirect_to :back
        else
        redirect_to order_path(id: @order.id)
      end

      else
      redirect_to order_path(id: @order.id)
    end
  end

  def activate_order
    @order = Pedido.find_by_codigo(params[:code])
    @order.activacion_de_pedido = true
    @order.estatus_del_pedido = "En almacen"
    @order.save
    redirect_to :back
  end

  def finish_order
    @order = Pedido.find_by_codigo(params[:code])
    @order.finalizacion_de_pedido = true
    @order.estatus_del_pedido = "Pedido finalizado"
    @order.save
    redirect_to :back
  end

  def send_order
    @order = Pedido.find_by_codigo(params[:code])
    @order.estatus_del_pedido = "En trayecto"
    @order.save
    redirect_to :back
  end



  def acount_information
    @customer = CustomerRegister.find_by_customer_email(params[:email])
    @orders = @customer.pedidos.last(10)
  end

  def shipments
  end

  def shipment
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_orders.html.erb
<table class="table table-bordered table-shop">
	<caption><%= caption %></caption>
	<thead>
		<tr>
			<th>Codigo interno</th>
			<th>Codigo de pago</th>
			<th>Nombre</th>
			<th>Email</th>
			<th>Teléfono</th>
			<th>Metodo de pago</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% orders.each do |order| %>
		<tr>
			<td><%= order.codigo %></td>
			<td><%= order.conekta_order %></td>
			<td><%= "#{order.nombre_persona_que_ordena} #{order.apellidos_persona_que_ordena} "%></td>
			<td><%= order.email %></td>
			<td><%= order.telefono_celular %></td>
			<td><%= order.metodo_de_pago %></td>
			<td> <%= link_to 'Mas datos...', order_path(id: order.id)%> </td>
		</tr>
		<%end%>
	</tbody>
</table>

app/views/customers/acount_information.html.erb
<h1>Cliente: <%= @customer.customer_name %></h1>
<table class="table table-bordered table-shop">
	<thead>
		<tr>
		<th>
		Variable
		</th>
		<th>
		Dato
		</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Id</td>
			<td><%= @customer.customer_token_conekta %></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><%= @customer.customer_email %></td>
		</tr>
		<tr>
			<td>Teléfono</td>
			<td><%= @customer.customer_phone %></td>
		</tr>
	</tr>
</tbody>
</table>

<%= render partial: 'customers/orders', locals: {caption: "Últimas ordenes del cliente", orders: @orders}%>

app/views/customers/finish_orders.html.erb
<h1>Ordenes finalizadas</h1>
<%= form_tag find_orders_path do -%>
<div class="form-group">
	<div class="input-group input-group-md">
		<input type="text" name="search" class="form-control" placeholder="Buscar ... ">
		<span class="input-group-btn">
			<button type="submit" class="btn btn-success"><i class="fa fa-search" aria-hidden="true"></i> Buscar Orden</button>
		</span>
	</div>
</div>
<%end%>
<%= render partial: 'customers/orders', locals: {caption: "Tabla de ordenes", orders: @orders}%>
<%= will_paginate @orders, :previous_label => '← Anterior', :next_label => 'Siguiente →', renderer: BootstrapPagination::Rails %>

app/views/customers/in_send_orders.html.erb
<h1>Ordenes en proceso de envio</h1>
<%= form_tag find_orders_path do -%>
<div class="form-group">
	<div class="input-group input-group-md">
		<input type="text" name="search" class="form-control" placeholder="Buscar ... ">
		<span class="input-group-btn">
			<button type="submit" class="btn btn-success"><i class="fa fa-search" aria-hidden="true"></i> Buscar Orden</button>
		</span>
	</div>
</div>
<%end%>
<%= render partial: 'customers/orders', locals: {caption: "Tabla de ordenes", orders: @orders}%>
<%= will_paginate @orders, :previous_label => '← Anterior', :next_label => 'Siguiente →', renderer: BootstrapPagination::Rails %>

app/views/customers/index.html.erb
<h1>Clientes</h1>
<table class="table table-bordered table-shop">
	<caption>tabla de clientes</caption>
	<thead>
		<tr>
			<th>Id</th>
			<th>Nombre</th>
			<th>Email</th>
			<th>Teléfono</th>
		    <th colspan="2"></th>
		</tr>
	</thead>
	<tbody>
	    <% @customers.each do |customer| %>
		<tr>

			<td><%= customer.customer_token_conekta %></td>
			<td><%= customer.customer_name %></td>
			<td><%= customer.customer_email %></td>
			<td><%= customer.customer_phone %></td>
			<td><%= link_to orders_path(customer: customer.customer_token_conekta) do %>Ordenes<%end%></td>
			<td><%= link_to acount_path(email: customer.customer_email) do %>Cuenta <%end%></td>
		</tr>
		<%end%>
	</tbody>
</table>
<%= will_paginate @customers, :previous_label => '← Anterior', :next_label => 'Siguiente →', renderer: BootstrapPagination::Rails %>

app/views/customers/inprocess_orders.html.erb
<h1>Ordenes en proceso</h1>
<%= form_tag find_orders_path do -%>
<div class="form-group">
	<div class="input-group input-group-md">
		<input type="text" name="search" class="form-control" placeholder="Buscar ... ">
		<span class="input-group-btn">
			<button type="submit" class="btn btn-success"><i class="fa fa-search" aria-hidden="true"></i> Buscar Orden</button>
		</span>
	</div>
</div>
<%end%>
<%= render partial: 'customers/orders', locals: {caption: "Tabla de ordenes", orders: @orders}%>
<%= will_paginate @orders, :previous_label => '← Anterior', :next_label => 'Siguiente →', renderer: BootstrapPagination::Rails %>

app/views/customers/montly_orders.html.erb
<h1>Pedidos de este mes - <%= @orders.count %></h1>
<%= form_tag find_orders_path do -%>
<div class="form-group">
	<div class="input-group input-group-md">
		<input type="text" name="search" class="form-control" placeholder="Buscar ... ">
		<span class="input-group-btn">
			<button type="submit" class="btn btn-success"><i class="fa fa-search" aria-hidden="true"></i> Buscar Orden</button>
		</span>
	</div>
</div>
<%end%>
<br/>
<%= link_to  montly_orders_path(format: "csv"), class: 'btn btn-info pull-right' do%>
<i class="fa fa-cloud-download" aria-hidden="true"></i> Descargar datos Mensuales
<%end%>
<%if @orders.count != 0  %>
<%= render partial: 'customers/orders', locals: {caption: "Tabla de ordenes del mes", orders: @orders}%>
<%= will_paginate @orders, :previous_label => '← Anterior', :next_label => 'Siguiente →', renderer: BootstrapPagination::Rails %>
<%else%>
<center>
<p>No se han encontrado ordenes para este mes</p>
</center>
<%end%>

app/views/customers/order.html.erb
<h1>Orden <%= @order.codigo %></h1>
<div class="col-lg-12">
	<div class="btn-group pull-right">
		<%= link_to 'Activar pedido', activate_order_path(code: @order.codigo), class: 'btn btn-success' unless @order.activacion_de_pedido %>

		<% unless @order.finalizacion_de_pedido %>
		<% if @order.estatus_del_pedido == "En trayecto" %>
		<%= link_to 'Finalizar pedido', finish_order_path(code: @order.codigo), class: 'btn btn-warning' if @order.activacion_de_pedido %>
		<%end%>
		<%end%>

		<% if @order.activacion_de_pedido %>
		<% if @order.estatus_del_pedido == "En almacen" %>
		<%= link_to send_order_path(code: @order.codigo), class: 'btn btn-default'  do%>
		 Enviar pedido <i class="fa fa-truck" aria-hidden="true"></i>
		<%end%>
		<%end%>
		<%end%>
	</div>
</div>
<div class="col-lg-12">
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#orden" aria-controls="orden" role="tab" data-toggle="tab">Orden de compra</a></li>
		<li role="presentation"><a href="#envio" aria-controls="envio" role="tab" data-toggle="tab">Datos de envio y estado</a></li>
	</ul>
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="orden">
			<table class="table table-bordered table-shop">
				<caption>Orden de compra</caption>
				<thead>
					<tr>
						<th>Codigo interno</th>
						<th>Codigo de pago</th>
						<th>Nombre</th>
						<th>Email</th>
						<th>Teléfono</th>
						<th>Metodo de pago</th>
						<th>Estatus del pago</th>
						<th>Monto Bancario del pago</th>
						<th>Fecha de creación</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= @order.codigo %></td>
						<td><%= @order.conekta_order %></td>
						<td><%= "#{@order.nombre_persona_que_ordena} #{@order.apellidos_persona_que_ordena} "%></td>
						<td><%= @order.email %></td>
						<td><%= @order.telefono_celular %></td>
						<td><%= @order.metodo_de_pago %></td>
						<td><%= @order.status.payment_status if @order.status != nil %></td>
						<td>$<%= @order.status.amount/100 if @order.status != nil %> <%= @order.status.currency if @order.status != nil %></td>
						<td><%= @order.created_at.strftime('%D %R') %></td>
					</tr>
				</tbody>
			</table>
			<table class="table table-bordered table-shop table-striped">
				<caption>Tabla de productos</caption>
				<thead>
					<tr>
						<th>Producto</th>
						<th>Color</th>
						<th>Unitario</th>
						<th>Cantidad </th>
						<th>Totales</th>
					</tr>
				</thead>
				<tbody>
					<% @order.productos_a_pedidos.each do |pp| %>
					<tr>
						<td><%= link_to pp.product.nombre, product_path(pp.product_id), target: '_blank' %></td>
						<td><% eval(pp.color).each do |color| %>
							<ul>
								<li><%=color%></li>
							</ul>
							<%end%>
						</td>
						<td>$<%= pp.product.precio %> MXN</td>
						<td><%= pp.quanty %></td>
						<td>$<%= pp.total_price %> MXN</td>
					</tr>
					<%end%>
				</tbody>
			</table>
		</div>
		<div role="tabpanel" class="tab-pane" id="envio">
			<table class="table table-bordered table-shop table-striped">
				<caption>Tabla de pedido</caption>
				<thead>
					<tr>
						<th>Concepto</th>
						<th>Dato</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Creado</td>
						<td><%= @order.created_at.strftime('%D %R') %></td>
					</tr>
					<tr>
						<td>Actualizado</td>
						<td><%= @order.updated_at.strftime('%D %R') %></td>
					</tr>
					<tr>
						<td>Dirección</td>
						<td><%= @order.direccion %></td>
					</tr>
					<tr>
						<td>Calle</td>
						<td><%= @order.calle %></td>
					</tr>
					<tr>
						<td>Colonia</td>
						<td><%= @order.colonia %></td>
					</tr>
					<tr>
						<td>Número Exterior</td>
						<td><%= @order.numero_exterior %></td>
					</tr>
					<tr>
						<td>Número Interior</td>
						<td><%= @order.numero_interior %></td>
					</tr>
					<tr>
						<td>Código postal</td>
						<td><%= @order.cpostal %></td>
					</tr>
					<tr>
						<td>Localidad</td>
						<td><%= @order.localidad %></td>
					</tr>
					<tr>
						<td>Estado</td>
						<td><%= @order.estado %></td>
					</tr>
					<tr>
						<td>País</td>
						<% if @order.pais.nil? %>
						<td>México</td>
						<%else%>
						<td><%= @order.pais %></td>
						<%end%>
					</tr>
					<tr>
						<td>Método de envio</td>
						<td><%= @order.metodo_de_envio %></td>
					</tr>
					<tr>
						<td>Costo de envio</td>
						<td><%= @order.costo_de_envio %></td>
					</tr>
					<tr>
						<td>Activación del pedido</td>
						<td><%= @order.activacion_de_pedido %></td>
					</tr>
					<tr>
						<td>Finalización del pedido</td>
						<td><%= @order.finalizacion_de_pedido %></td>
					</tr>
					<tr>
						<td>Estatus del pedido</td>
						<td><%= @order.estatus_del_pedido %></td>
					</tr>
					<tr>
						<td>Aceptación de términos el pedido</td>
						<td><%= @order.aceptacion_de_terminos %></td>
					</tr>
					<tr>
						<td>Email principal</td>
						<td><%= @order.email %></td>
					</tr>
					<tr>
						<td>Email secundario</td>
						<td><%= @order.email2 %></td>
					</tr>
					<tr>
						<td>Personas autorizadas a recoger</td>
						<td>
							<%= @order.persona_autorizada_a_recoger_1 %><br/>
							<%= @order.persona_autorizada_a_recoger_2 %><br/>
							<%= @order.persona_autorizada_a_recoger_3 %><br/>
							<%= @order.persona_autorizada_a_recoger_4 %><br/>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/customers/orders.html.erb
<h1>Ordenes o Pedidos</h1>
<%= form_tag find_orders_path do -%>
<div class="form-group">
	<div class="input-group input-group-md">
		<input type="text" name="search" class="form-control" placeholder="Buscar ... ">
		<span class="input-group-btn">
			<button type="submit" class="btn btn-success"><i class="fa fa-search" aria-hidden="true"></i> Buscar Orden</button>
		</span>
	</div>
</div>
<%end%>
<%= render partial: 'customers/orders', locals: {caption: "Tabla de ordenes", orders: @orders}%>
<%= will_paginate @orders, :previous_label => '← Anterior', :next_label => 'Siguiente →', renderer: BootstrapPagination::Rails %>

app/views/customers/shipment.html.erb
<h1>Customers#shipment</h1>
<p>Find me in app/views/customers/shipment.html.erb</p>

app/views/customers/shipments.html.erb
<h1>Customers#shipments</h1>
<p>Find me in app/views/customers/shipments.html.erb</p>

app/views/customers/today_orders.html.erb
<h1>Pedidos de hoy - <%= @orders.count %></h1>
<%= form_tag find_orders_path do -%>
<div class="form-group">
	<div class="input-group input-group-md">
		<input type="text" name="search" class="form-control" placeholder="Buscar ... ">
		<span class="input-group-btn">
			<button type="submit" class="btn btn-success"><i class="fa fa-search" aria-hidden="true"></i> Buscar Orden</button>
		</span>
	</div>
</div>
<%end%>
<br/>
<%= link_to  montly_orders_path(format: "csv"), class: 'btn btn-info pull-right' do%>
<i class="fa fa-cloud-download" aria-hidden="true"></i> Descargar datos del día
<%end%>
<%if @orders.count != 0  %>
<%= render partial: 'customers/orders', locals: {caption: "Tabla de ordenes del día", orders: @orders}%>
<%= will_paginate @orders, :previous_label => '← Anterior', :next_label => 'Siguiente →', renderer: BootstrapPagination::Rails %>
<%else%>
<center>
<p>No se han encontrado ordenes para hoy</p>
</center>
<%end%>