config/routes.rb
Rails.application.routes.draw do
  root 'tienda#index'
  get '/terminos_y_condiciones', to: 'tienda#terminos_y_condiciones', as: :terminos
  get '/aviso_de_privacidad', to: 'tienda#aviso_de_privacidad', as: :aviso_de_privacidad
  get 'tienda/fancy', as: :fancy
  get 'tienda/generate_subscriber', as: :generate_subscriber
  post 'tienda/generate_subscriber'
  devise_for :users
  resources :products, path: 'admin/products'
  get 'admin/customers', to: 'customers#index',as: :customers
  get 'admin/orders', to: 'customers#orders', as: :orders
  get 'admin/order/:id', to: 'customers#order', as: :order
  get 'admin/customers/acount', to: 'customers#acount_information', as: :acount
  get 'admin/shipments', to: 'customers#shipments',as: :shipments
  get 'admin/shipment', to: 'customers#shipment', as: :shipment
  get 'admin/find_orders', to: 'customers#find_orders', as: :find_orders
  post 'admin/find_orders', to: 'customers#find_orders'
  get 'admin/import_products', to: 'products#import_products', as: :import_products
  post 'admin/import_products', to: 'products#import_products'
  get 'admin/today_orders', to: 'customers#today_orders', as: :today_orders
  get 'admin/montly_orders', to: 'customers#montly_orders', as: :montly_orders
  get 'admin/inprocess_orders', to: 'customers#inprocess_orders', as: :inprocess_orders
  get 'admin/finish_orders', to: 'customers#finish_orders', as: :finish_orders
  get 'admin/in_send_orders', to: 'customers#in_send_orders', as: :in_send_orders
  get 'admin/activate_order', to: 'customers#activate_order', as: :activate_order
  post 'admin/activate_order', to: 'customers#activate_order'
  get 'admin/send_order', to: 'customers#send_order', as: :send_order
  post 'admin/send_order', to: 'customers#send_order'
  get 'admin/finish_order', to: 'customers#finish_order', as: :finish_order
  post 'admin/finish_order', to: 'customers#finish_order'
  get 'admin/admins',to: 'admins#index', as: :admins
  get 'admin/admins/new',   to: 'admins#new', as: :new_admin
  get 'admin/admins/create',   to: 'admins#create', as: :create
  post 'admin/admins/create',   to: 'admins#create'
  get 'admin/admins/edit',  to: 'admins#edit', as: :edit_admin
  get 'admin/admins/destroy',  to: 'admins#destroy', as: :destroy_admin
  get 'admin/admins/update_admin', to: 'admins#update_admin', as: :update_admin
  post 'admin/admins/update_admin', to: 'admins#update_admin'
  get 'admin/login', to: "admins#login_admin", as: :login
  get 'admin', to: "admins#admin", as: :admin_i
  get 'admin/admins/verify_pass', to: "admins#verify_pass", as: :verify_pass
  post 'admin/admins/verify_pass', to: "admins#verify_pass"
  get 'admin/admins/log_out', to: "admins#log_out", as: :log_out
  get 'all_items', to: 'tienda#productos', as: :all_items
  get 'search', to: 'tienda#search', as: :search
  get 'item-in-stock/:id', to: 'tienda#producto', as: :item
  get 'tienda/carrito'
  get 'tienda/confirmacion_pago', as: :confirmacion_pago
  get 'tienda/lista_de_productos', as: :lista_de_productos
  get 'tienda/actualizar_carrito', as: :actualizar_carrito
  get 'tienda/eliminar_items_del_carrito', as: :eliminar_items_del_carrito
  get 'tienda/crear_pedido', as: :crear_pedido
  post 'tienda/crear_pedido' 
  get 'tienda/buscar_pedido', as: :buscar_pedido
  post 'tienda/buscar_pedido'
  get 'tienda/ver_pedido', as: :ver_pedido
  post 'tienda/ver_pedido'
  get 'tienda/producto_no_encontrado', as: :producto_no_encontrado
  post 'tienda/producto_no_encontrado'
  get 'tienda/contacto', as: :contacto
  post 'tienda/contacto'
  get 'tienda/contactado', as: :contactado
  post 'tienda/contactado'
  get 'tienda/eliminar_item', as: :eliminar_item
  get 'tienda/offers', as: :offers
  get 'nosotros', to: 'tienda#nosotros', as: :about_us
  get 'admin/products/:id/products_photos',to: 'products#products_photos', as: :gallery
  get 'admin/products/:id/add_photos',to: 'products#add_photos', as: :add_photos
  post 'admin/products/:id/add_photos',to: 'products#add_photos'
  get 'admin/productos_no_publicados',to: 'products#productos_no_publicados', as: :productos_no_publicados
  post 'admin/productos_no_publicados',to: 'products#productos_no_publicados'
  get 'admin/eliminar_todos_los_productos_sin_publicar',to: 'products#eliminar_todos_los_productos_sin_publicar', as: :eliminar_todos_los_productos_sin_publicar
  post 'admin/eliminar_todos_los_productos_sin_publicar',to: 'products#eliminar_todos_los_productos_sin_publicar'
  get 'admin/destroy_photos/:id',to: 'products#destroy_photos', as: :destroy_photos
  post 'admin/destroy_photos/:id',to: 'products#destroy_photos'
  get 'admin/products/:id/activate_inactive',to: 'products#activate_inactive', as: :active_inactive
  post 'admin/products/:id/activate_inactive',to: 'products#activate_inactive'
  get 'admin/search_product', to: 'products#search_product', as: :search_product
  post 'admin/search_product', to: 'products#search_product' 
  get 'admin/active_all',to: 'products#active_all', as: :active_all
  post 'admin/active_all',to: 'products#active_all'
  get 'admin/unactive_all',to: 'products#unactive_all', as: :unactive_all
  post 'admin/unactive_all',to: 'products#unactive_all'
  get 'admin/products_import_list', to: 'products#import_list', as: :import_list
  get 'admin/categoria-de-producto', to: 'products#categoria', as: :categoria
  get 'admin/nueva_etiqueta',  to: 'tags_and_categories#nueva_etiqueta', as: :nueva_etiqueta 
  get 'payments/payment_proccess', as: :payment_proccess
  post 'payments/payment_proccess'
  get 'payments/tarjeta', as: :tarjeta
  post 'payments/tarjeta'
  get 'payments/oxxo', as: :oxxo
  post 'payments/oxxo'

  ######## api routes ########
  get 'api/list_products', :defaults => { :format => 'json' }
  get 'api/best_produtcs', :defaults => { :format => 'json' }
  get 'api/my_products', :defaults => { :format => 'json' }
  get 'api/categorias', :defaults => { :format => 'json' }
  post 'api/my_products', :defaults => { :format => 'json' }
  post 'api/image_products', :defaults => { :format => 'json' }
  get 'api/search', :defaults => { :format => 'json' }
  post 'api/favoritos', :defaults => { :format => 'json' }
  post 'api/generate_mobile_order', :defaults => { :format => 'json' }
  post 'api/tarjeta_pago_mobil', :defaults => { :format => 'json' }
  get 'api/find_order', :defaults => { :format => 'json' }



end

app/models/product.rb
require 'wikipedia'

Wikipedia.Configure {
  domain 'es.wikipedia.org'
  path   'w/api.php'
}
class Product < ApplicationRecord
	has_many :category_products_and_products
    has_many :category_products, through: :category_products_and_products
    has_many :image_products
    has_many :productos_a_pedidos
    scope :nombre, lambda { |nombre| where(["nombre ILIKE ?", "%#{nombre}%"])}
    scope :nombre_cientifico, lambda { |nombre_cientifico| where(["nombre_cientifico ILIKE ?", "%#{nombre_cientifico}%"])}
    scope :pais_de_procedencia, lambda { |pais_de_procedencia| where(["pais_de_procedencia ILIKE ?", "%#{pais_de_procedencia}%"])}
    scope :familia, lambda { |familia| where(["familia ILIKE ?", "%#{familia}%"])}
    scope :categoria_principal_interna, lambda { |categoria_principal_interna| where(["categoria_principal_interna ILIKE ?", "%#{categoria_principal_interna}%"])}
    scope :orden, lambda { |orden| where(["orden ILIKE ?", "%#{orden}%"])}
    scope :color1, lambda { |color1| where(["color1 ILIKE ?", "%#{color1}%"])}
    scope :color2, lambda { |color2| where(["color2 ILIKE ?", "%#{color2}%"])}
    scope :color3, lambda { |color3| where(["color3 ILIKE ?", "%#{color3}%"])}
    scope :color4, lambda { |color4| where(["color4 ILIKE ?", "%#{color4}%"])}
    scope :color5, lambda { |color5| where(["color5 ILIKE ?", "%#{color5}%"])}
    scope :region_climatica, lambda { |region_climatica| where(["region_climatica LIKE ?", "%#{region_climatica}%"])}
    scope :luz, lambda { |luz| where(["luz LIKE ?", "%#{luz}%"])}
    scope :riego, lambda { |riego| where(["riego LIKE ?", "%#{riego}%"])}


    def wikipedia_link
      if self.nombre_cientifico != nil
    	page = Wikipedia.find( "#{self.nombre_cientifico}" )
      if page != nil
    	@url = page.fullurl
      else
      @url = ''
      end
      else
      @url = ''
      end

    end

    def wikipedia_content
      if self.nombre_cientifico != nil
    	page = Wikipedia.find( "#{self.nombre_cientifico}" )
      if page != nil
    	  @text = page.text
         if @text == nil 
          @text = 'No se encontro información para este producto...'
          else
          @text = @text
         end
      else
       @text = 'No se encontro información para este producto...'
      end
      else
      @text = ''
      end

    end

    def descuento
       if !self.oferta.nil?
       oferta = self.oferta.to_f / 100
       descuento = self.precio.to_f * oferta.to_f
       descuento = descuento.round(2)
       else
        descuento = 0
       end

    end

    def precio_final
       precio_final = self.precio.to_f - descuento.to_f
       precio_final = precio_final.round()
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout 'admin'
  before_action :set_product, only: [:show, :edit, :update, :destroy, :products_photos, :add_photos]
  before_filter :admin_filter

  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(:page => params[:page], :per_page => 50)
  end

  def productos_no_publicados
    @products = Product.where(publicado: false).paginate(:page => params[:page], :per_page => 50)
  end

  def eliminar_todos_los_productos_sin_publicar
    @products = Product.where(publicado: false)
    @products.each do |p|
      p.destroy
    end
    redirect_to :back
  end


  def products_photos
  end

  def search_product
    @products = Product.all
    @products = @products.nombre(params[:search]) if params[:search].present?
    if @products.count == 0
      @products = Product.all
      @products = @products.nombre_cientifico(params[:search]) if params[:search].present?
    end
  end


  def add_photos 
    params[:file].each do |file|
      puts "++++++++"
      puts "#{file}"
      @image = ImageProduct.new
      @image.product_id = @product.id
      @image.file = file
      @image.save
    end
    redirect_to :back
  end

  def destroy_photos
    @image = ImageProduct.find(params[:id])
    @image.destroy
    redirect_to :back
  end
  
  def import_list
  end

  def import_products
    require 'csv' 
    file = params[:file]
    uploaded_io = file
    File.open(Rails.root.join('tmp', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end


    csv_text = File.read("#{Rails.root}/tmp/uploads/#{uploaded_io.original_filename}")
    csv = CSV.parse(csv_text, :headers => true)
    csv.each do |row|
      Product.create!(row.to_hash)
    end
    redirect_to root_url, notice: 'Productos importados.'
  end

  def categoria
     @products = Product.where(categoria_principal_interna: params[:categoria]).paginate(:page => params[:page], :per_page => 20)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def activate_inactive
   product = Product.find(params[:id])
   if product.publicado
     product.publicado = false
   else
      if product.image_products.count != 0
      puts "El producto se publicara"
      product.publicado = true
       else
      puts "Productos sin imagenes"
     end
   end
  
   product.save

   redirect_to :back
  end

  def active_all
    products = Product.where(publicado: false)

    products.each do |product|
      if product.image_products.count != 0
        product.publicado = true
        product.save 
      end
    end
    
    redirect_to :back
  end

  def unactive_all
    Product.update_all publicado: false
    redirect_to :back
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    puts params[:product][:file]
    if @product.save
        params[:product][:file].each do |file|
          puts "++++++++"
          puts "#{file}"
          @image = ImageProduct.new
          @image.product_id = @product.id
          @image.file = file
          @image.save
        end
    end

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_path(@product.id), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:nombre, :precio, :nombre_cientifico, :luz, :riego, :necesidades, :descripccion, :tamano, :region_climatica, :pais_de_procedencia, :familia, :orden, :categoria_principal_interna, :publicado, :color1, :color2, :color3, :color4, :color5, :name_downcase_no_characters, :file, :oferta)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_categoria.html.erb
<select name="product[categoria_principal_interna]" class="form-control">
    <% $CATEGORIAS.each do |categoria| %>
	<option value="<%= categoria[:serach]%>"><%= categoria[:name] %></option>
    <%end%>
</select>

app/views/products/_search_products.html.erb
<%= form_tag search_product_path do -%>
<div class="form-group">
	<div class="input-group input-group-md">
		<input type="text" name="search" class="form-control" placeholder="Buscar por nombre y o por nombre científico ... ">
		<span class="input-group-btn">
			<button type="submit" class="btn btn-success"><i class="fa fa-search" aria-hidden="true"></i> Buscar producto</button>
		</span>
	</div>
</div>
<%end%>

app/views/products/edit.html.erb
<h1>Editar Producto</h1>
<%= render 'form', product: @product %>

app/views/products/import_list.html.erb
<h1>Importación de una lista de productos.</h1>
<div class="col-md-5">
<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Importación", class: 'btn btn-default pull-right' %>
<% end %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Lista de productos</h1>
<h3>Productos: <%=Product.count %></h3>
<div class="btn-group pull-right">
  <%= link_to active_all_path, data: { confirm: '¿Estas segur@ de querer activar todos los productos?' } , class: 'btn btn-success btn-small' do %>
  Activar todos los producto  <i class="fa fa-toggle-on" aria-hidden="true"></i>
  <%end%>
  <%= link_to unactive_all_path, data: { confirm: '¿Estas segur@ de querer desactivar todos los  productos?' }, class: 'btn btn-warning btn-small'  do %>
  Desactivar todos los productos <i class="fa fa-toggle-off" aria-hidden="true"></i>
  <%end%>
</div>
<br/><br/>
<table class="table table-bordered table-shop">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Nombre cientifico</th>
      <th>Tamaño</th> 
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.nombre %></td>
      <td><%= product.precio %></td>
      <td><%= product.nombre_cientifico %></td>
      <td><%= product.tamano %></td>
      <center>
      <td>
        <%= link_to product, class: "btn btn-success",  "data-toggle": "tooltip", "data-placement": "top", "title": "Ver datos del producto"  do %>
        <i class="fa fa-folder-open" aria-hidden="true"></i>
        <%end%>
      </td>
      <td>
        <%= link_to edit_product_path(product), class: "btn btn-info",  "data-toggle": "tooltip", "data-placement": "top", "title": "Editar producto" do %>
        <i class="fa fa-pencil" aria-hidden="true"></i>
        <%end%>
      </td>
      <td>
        <%= link_to gallery_path(product), class: "btn btn-default",  "data-toggle": "tooltip", "data-placement": "top", "title": "Imagenes del producto" do %>
        <i class="fa fa-camera-retro" aria-hidden="true"></i>
        <%end%>
      </td>
      <td>
        <% if product.publicado %>
        <%= link_to active_inactive_path(id: product.id), class: 'btn btn-success btn-small',  "data-toggle": "tooltip", "data-placement": "top", "title": "Cambiar estado de activación del producto" do %>
        <i class="fa fa-toggle-on" aria-hidden="true"></i>
        <%end%>
        <%else%>
        <%= link_to active_inactive_path(id: product.id), class: 'btn btn-warning btn-small',  "data-toggle": "tooltip", "data-placement": "top", "title": "Cambiar estado de activación del producto"  do %>
        <i class="fa fa-toggle-off" aria-hidden="true"></i>
        <%end%>
        <%end%>
      </td>
      
      <td><%= link_to  product, method: :delete, data: { confirm: '¿Estas segur@ de eliminar el producto?' }, class: "btn btn-danger",  "data-toggle": "tooltip", "data-placement": "top", "title": "Eliminar producto"  do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
        <%end%>
      </td>
      </center>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<center>
<%= will_paginate @products, :previous_label => '← Anterior', :next_label => 'Siguiente →', renderer: BootstrapPagination::Rails %>
</center>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>

app/views/products/new.html.erb
<h1>Crear un producto</h1>

<%= render 'create_form', product: @product %>

<%#= link_to 'Back', products_path %>

app/views/products/productos_no_publicados.html.erb
<p id="notice"><%= notice %></p>
<h1>Lista de productos</h1>
<h3>Productos: <%=@products.count %></h3>
<%= link_to 'Eliminar todos los productos sin publicar', eliminar_todos_los_productos_sin_publicar_path, data: { confirm: '¿Estas segur@ de eliminar todos los productos sin publicar?' } %>

<div class="btn-group pull-right">
  <%= link_to active_all_path, data: { confirm: '¿Estas segur@ de querer activar todos los productos?' } , class: 'btn btn-success btn-small' do %>
  Activar todos los producto  <i class="fa fa-toggle-on" aria-hidden="true"></i>
  <%end%>
  <%= link_to unactive_all_path, data: { confirm: '¿Estas segur@ de querer desactivar todos los  productos?' }, class: 'btn btn-warning btn-small'  do %>
  Desactivar todos los productos <i class="fa fa-toggle-off" aria-hidden="true"></i>
  <%end%>
</div>
<br/><br/>
<table class="table table-bordered table-shop">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Nombre cientifico</th>
      <th>Tamaño</th> 
      <th>Imagenes</th> 
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.nombre %></td>
      <td><%= product.precio %></td>
      <td><%= product.nombre_cientifico %></td>
      <td><%= product.tamano %></td>
      <td><%= product.image_products.count %></td>
      <center>
      <td>
        <%= link_to product, class: "btn btn-success",  "data-toggle": "tooltip", "data-placement": "top", "title": "Ver datos del producto"  do %>
        <i class="fa fa-folder-open" aria-hidden="true"></i>
        <%end%>
      </td>
      <td>
        <%= link_to edit_product_path(product), class: "btn btn-info",  "data-toggle": "tooltip", "data-placement": "top", "title": "Editar producto" do %>
        <i class="fa fa-pencil" aria-hidden="true"></i>
        <%end%>
      </td>
      <td>
        <%= link_to gallery_path(product), class: "btn btn-default",  "data-toggle": "tooltip", "data-placement": "top", "title": "Imagenes del producto" do %>
        <i class="fa fa-camera-retro" aria-hidden="true"></i>
        <%end%>
      </td>
      <td>
        <% if product.publicado %>
        <%= link_to active_inactive_path(id: product.id), class: 'btn btn-success btn-small',  "data-toggle": "tooltip", "data-placement": "top", "title": "Cambiar estado de activación del producto" do %>
        <i class="fa fa-toggle-on" aria-hidden="true"></i>
        <%end%>
        <%else%>
        <%= link_to active_inactive_path(id: product.id), class: 'btn btn-warning btn-small',  "data-toggle": "tooltip", "data-placement": "top", "title": "Cambiar estado de activación del producto"  do %>
        <i class="fa fa-toggle-off" aria-hidden="true"></i>
        <%end%>
        <%end%>
      </td>
      
      <td><%= link_to  product, method: :delete, data: { confirm: '¿Estas segur@ de eliminar el producto?' }, class: "btn btn-danger",  "data-toggle": "tooltip", "data-placement": "top", "title": "Eliminar producto"  do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
        <%end%>
      </td>
      </center>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<center>
<%= will_paginate @products, :previous_label => '← Anterior', :next_label => 'Siguiente →', renderer: BootstrapPagination::Rails %>
</center>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>

app/views/products/products_photos.html.erb
<h1>Imagenes - <%=@product.nombre %></h1>
<div class="col-lg-12">
	<div class="row">
		<div class="col-md-5 panel panel-default" style="padding: 20px; background: #f1f1f1;">
			<%= form_tag add_photos_path(@product), multipart: true, id: 'images-product' do -%>
			
			<div class="col-md-9">
				<%= file_field_tag 'file[]', multiple: true %>
			</div>
			<div class="col-md-2">
				<button type="submit" class="btn btn-info">
				<i class="fa fa-upload" aria-hidden="true"></i>
				</button>
			</div>
			
			<%end%>
		</div>
		<div class="col-md-7">
			<div class="btn-group pull-right">
			 <%= link_to @product, class: "btn btn-success",  "data-toggle": "tooltip", "data-placement": "top", "title": "Ver datos del producto"  do %>
	              <i class="fa fa-folder-open" aria-hidden="true"></i>
	         <%end%>
	         <%= link_to edit_product_path(@product), class: "btn btn-info",  "data-toggle": "tooltip", "data-placement": "top", "title": "Editar producto" do %>
                 <i class="fa fa-pencil" aria-hidden="true"></i>
             <%end%>
             <%= link_to gallery_path(@product), class: "btn btn-default",  "data-toggle": "tooltip", "data-placement": "top", "title": "Imagenes del producto" do %>
	             <i class="fa fa-camera-retro" aria-hidden="true"></i>
	        <%end%>
	         <% if @product.publicado %>
	        <%= link_to active_inactive_path(id: @product.id), class: 'btn btn-success btn-small',  "data-toggle": "tooltip", "data-placement": "top", "title": "Cambiar estado de activación del producto" do %>
	        <i class="fa fa-toggle-on" aria-hidden="true"></i>
	        <%end%>
	        <%else%>
	        <%= link_to active_inactive_path(id: @product.id), class: 'btn btn-warning btn-small',  "data-toggle": "tooltip", "data-placement": "top", "title": "Cambiar estado de activación del producto"  do %>
	        <i class="fa fa-toggle-off" aria-hidden="true"></i>
	        <%end%>
	        <%end%>
	        <%= link_to  @product, method: :delete, data: { confirm: '¿Estas segur@ de eliminar el producto?' }, class: "btn btn-danger",  "data-toggle": "tooltip", "data-placement": "top", "title": "Eliminar producto"  do %>
       			 <i class="fa fa-trash-o" aria-hidden="true"></i>
        	<%end%>
        </div>
		</div>
	</div>
	<div class="row">
		<% @product.image_products.each do |img| %>
		<div class="col-xs-6 col-md-3">
			<div class="thumbnail">
				<img src="<%= img.file.big%>" alt="img.file">
				<div class="caption">
					<%= link_to "Borrar Imagen", destroy_photos_path(id: img.id), class: "btn btn-warning btn-large", data: { confirm: '¿Estas segur@ de eliminar esta fotografía?' }%>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>
<script type="text/javascript">
$('#images-product').submit(function(e){
var url = $('#images-product').attr('action');
var formData = new FormData($('#images-product')[0]);
$.ajax({
type: "POST",
url: url,
data: formData,
enctype: 'multipart/form-data',
processData: false,
contentType: false,
cache: false,
success: function(data)
{
alert('Se ha agregado correctamente el producto');
window.location.reload();
}
});
e.preventDefault()
});
</script>