config/routes.rb
Rails.application.routes.draw do
  root 'tienda#index'
  get '/terminos_y_condiciones', to: 'tienda#terminos_y_condiciones', as: :terminos
  get '/aviso_de_privacidad', to: 'tienda#aviso_de_privacidad', as: :aviso_de_privacidad
  get 'tienda/fancy', as: :fancy
  get 'tienda/generate_subscriber', as: :generate_subscriber
  post 'tienda/generate_subscriber'
  devise_for :users
  resources :products, path: 'admin/products'
  get 'admin/customers', to: 'customers#index',as: :customers
  get 'admin/orders', to: 'customers#orders', as: :orders
  get 'admin/order/:id', to: 'customers#order', as: :order
  get 'admin/customers/acount', to: 'customers#acount_information', as: :acount
  get 'admin/shipments', to: 'customers#shipments',as: :shipments
  get 'admin/shipment', to: 'customers#shipment', as: :shipment
  get 'admin/find_orders', to: 'customers#find_orders', as: :find_orders
  post 'admin/find_orders', to: 'customers#find_orders'
  get 'admin/import_products', to: 'products#import_products', as: :import_products
  post 'admin/import_products', to: 'products#import_products'
  get 'admin/today_orders', to: 'customers#today_orders', as: :today_orders
  get 'admin/montly_orders', to: 'customers#montly_orders', as: :montly_orders
  get 'admin/inprocess_orders', to: 'customers#inprocess_orders', as: :inprocess_orders
  get 'admin/finish_orders', to: 'customers#finish_orders', as: :finish_orders
  get 'admin/in_send_orders', to: 'customers#in_send_orders', as: :in_send_orders
  get 'admin/activate_order', to: 'customers#activate_order', as: :activate_order
  post 'admin/activate_order', to: 'customers#activate_order'
  get 'admin/send_order', to: 'customers#send_order', as: :send_order
  post 'admin/send_order', to: 'customers#send_order'
  get 'admin/finish_order', to: 'customers#finish_order', as: :finish_order
  post 'admin/finish_order', to: 'customers#finish_order'
  get 'admin/admins',to: 'admins#index', as: :admins
  get 'admin/admins/new',   to: 'admins#new', as: :new_admin
  get 'admin/admins/create',   to: 'admins#create', as: :create
  post 'admin/admins/create',   to: 'admins#create'
  get 'admin/admins/edit',  to: 'admins#edit', as: :edit_admin
  get 'admin/admins/destroy',  to: 'admins#destroy', as: :destroy_admin
  get 'admin/admins/update_admin', to: 'admins#update_admin', as: :update_admin
  post 'admin/admins/update_admin', to: 'admins#update_admin'
  get 'admin/login', to: "admins#login_admin", as: :login
  get 'admin', to: "admins#admin", as: :admin_i
  get 'admin/admins/verify_pass', to: "admins#verify_pass", as: :verify_pass
  post 'admin/admins/verify_pass', to: "admins#verify_pass"
  get 'admin/admins/log_out', to: "admins#log_out", as: :log_out
  get 'all_items', to: 'tienda#productos', as: :all_items
  get 'search', to: 'tienda#search', as: :search
  get 'item-in-stock/:id', to: 'tienda#producto', as: :item
  get 'tienda/carrito'
  get 'tienda/confirmacion_pago', as: :confirmacion_pago
  get 'tienda/lista_de_productos', as: :lista_de_productos
  get 'tienda/actualizar_carrito', as: :actualizar_carrito
  get 'tienda/eliminar_items_del_carrito', as: :eliminar_items_del_carrito
  get 'tienda/crear_pedido', as: :crear_pedido
  post 'tienda/crear_pedido' 
  get 'tienda/buscar_pedido', as: :buscar_pedido
  post 'tienda/buscar_pedido'
  get 'tienda/ver_pedido', as: :ver_pedido
  post 'tienda/ver_pedido'
  get 'tienda/producto_no_encontrado', as: :producto_no_encontrado
  post 'tienda/producto_no_encontrado'
  get 'tienda/contacto', as: :contacto
  post 'tienda/contacto'
  get 'tienda/contactado', as: :contactado
  post 'tienda/contactado'
  get 'tienda/eliminar_item', as: :eliminar_item
  get 'tienda/offers', as: :offers
  get 'nosotros', to: 'tienda#nosotros', as: :about_us
  get 'admin/products/:id/products_photos',to: 'products#products_photos', as: :gallery
  get 'admin/products/:id/add_photos',to: 'products#add_photos', as: :add_photos
  post 'admin/products/:id/add_photos',to: 'products#add_photos'
  get 'admin/productos_no_publicados',to: 'products#productos_no_publicados', as: :productos_no_publicados
  post 'admin/productos_no_publicados',to: 'products#productos_no_publicados'
  get 'admin/eliminar_todos_los_productos_sin_publicar',to: 'products#eliminar_todos_los_productos_sin_publicar', as: :eliminar_todos_los_productos_sin_publicar
  post 'admin/eliminar_todos_los_productos_sin_publicar',to: 'products#eliminar_todos_los_productos_sin_publicar'
  get 'admin/destroy_photos/:id',to: 'products#destroy_photos', as: :destroy_photos
  post 'admin/destroy_photos/:id',to: 'products#destroy_photos'
  get 'admin/products/:id/activate_inactive',to: 'products#activate_inactive', as: :active_inactive
  post 'admin/products/:id/activate_inactive',to: 'products#activate_inactive'
  get 'admin/search_product', to: 'products#search_product', as: :search_product
  post 'admin/search_product', to: 'products#search_product' 
  get 'admin/active_all',to: 'products#active_all', as: :active_all
  post 'admin/active_all',to: 'products#active_all'
  get 'admin/unactive_all',to: 'products#unactive_all', as: :unactive_all
  post 'admin/unactive_all',to: 'products#unactive_all'
  get 'admin/products_import_list', to: 'products#import_list', as: :import_list
  get 'admin/categoria-de-producto', to: 'products#categoria', as: :categoria
  get 'admin/nueva_etiqueta',  to: 'tags_and_categories#nueva_etiqueta', as: :nueva_etiqueta 
  get 'payments/payment_proccess', as: :payment_proccess
  post 'payments/payment_proccess'
  get 'payments/tarjeta', as: :tarjeta
  post 'payments/tarjeta'
  get 'payments/oxxo', as: :oxxo
  post 'payments/oxxo'

  ######## api routes ########
  get 'api/list_products', :defaults => { :format => 'json' }
  get 'api/best_produtcs', :defaults => { :format => 'json' }
  get 'api/my_products', :defaults => { :format => 'json' }
  get 'api/categorias', :defaults => { :format => 'json' }
  post 'api/my_products', :defaults => { :format => 'json' }
  post 'api/image_products', :defaults => { :format => 'json' }
  get 'api/search', :defaults => { :format => 'json' }
  post 'api/favoritos', :defaults => { :format => 'json' }
  post 'api/generate_mobile_order', :defaults => { :format => 'json' }
  post 'api/tarjeta_pago_mobil', :defaults => { :format => 'json' }
  get 'api/find_order', :defaults => { :format => 'json' }



end

app/views/layout_parts/_cat_list.html.erb
<% $CATEGORIAS.each do |categoria| %>
<li><a href="<%= search_path(search: categoria[:search]) %>"><%= truncate(categoria[:name], length: 25, separator: ' ', omission: '...')%></a></li>
<%end%>

app/views/layout_parts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<% if mobile_device? %>
		<div class="col-lg-12">
			<center>
			<br/>
			<%= image_tag('logos/520-full/verano.png', width: '50%') %><br/>
			<span class="text-muted">Ur Garden © Todos los derechos reservados <%=  DateTime.now.strftime('%Y')%> </span><br/>
			<%= link_to "Términos y Condiciones del sitio", terminos_path %><br/>
			<%= link_to "Aviso de privacidad", aviso_de_privacidad_path %><br/>
			<a  href="https://fb.me/UrGardenOficial" target="_blank">
				<i class="fa fa-facebook" aria-hidden="true"></i> Facebook
			</a><br/><br/>
			<br/>
			</center>
		</div>
		<%else%>
		<div class="col-lg-12">
			<div class="col-md-4">
				<div class="li-divition">
					Nosotros
				</div>
				<ul>
					<li>
						<%= link_to "¿Que es Ur.Garden?", about_us_path %>
					</li>
					<li>
						<%= link_to "Contactanos", "mailto:contactourgarden@gmail.com" %>
					</li>
					<!--<li>
						<%= link_to "Nosotros", about_us_path %>
					</li>
					<li>
						<%= link_to "Socios estratégicos", terminos_path %>
					</li>-->
				</ul>

				<div class="li-divition">
					Redes Sociales
				</div>
				<ul>
					<!--<li><a  href="https://twitter.com/ubergardenMX" target="_blank">
						<i class="fa fa-twitter" aria-hidden="true"></i> Twitter
					</a>  </li>-->
					<li><a  href="https://fb.me/UrGardenOficial" target="_blank">
						<i class="fa fa-facebook" aria-hidden="true"></i> Facebook
					</a>  </li>
					<li><a  href="https://m.me/UrGardenOficial." target="_blank">
						<i class="fa fa-facebook" aria-hidden="true"></i> Mensaje Facebook
					</a>  </li>
				</ul>
				
			</div>
			<div class="col-md-4">
				<div class="li-divition">
					Legal
				</div>
				<ul>
					<li>
						<%= link_to "Términos y Condiciones del sitio", terminos_path %>
					</li>
					<li>
						<%= link_to "Aviso de privacidad", aviso_de_privacidad_path %>
					</li>
				</ul>
				<a href='https://www.expeditedssl.com/simple-ssl-scanner/scan?target_domain=www.urgarden.com.mx' target='_blank' rel='nofollow'><img src='https://www.expeditedssl.com/ssl-secure-badge.png'  alt='Expedited SSL Scanner'></a>
				
				<!--<div class="li-divition">
					Teléfono de contacto
				</div>
				<ul>
					<li><a  href="https://twitter.com/ubergardenMX" target="_blank">
						<i class="fa fa-phone" aria-hidden="true"></i> 5555-5555
					</a>  </li>
					<li><a  href="https://fb.me/ubergardenMX" target="_blank">
						<i class="fa fa-phone" aria-hidden="true"></i> 4444-4444
					</a>  </li>
				</ul>-->
			</div>
			<div class="col-md-4">
				<br/><br/>
				<center>
				<br/>
				<%= image_tag('logos/520-full/verano.png', width: '50%') %><br/>
				<span class="text-muted">Ur Garden © Todos los derechos reservados <%=  DateTime.now.strftime('%Y')%> </span>
				<br/>
				</center>
				<br/><br/>
			</div>
		</div>
		<%end%>
	</div>
</footer>

app/views/layout_parts/_head_admin.html.erb
<nav class="navbar navbar-default navbar-static-top">
	<div class="container-fluid">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<%= link_to products_path do %>
				<div style="margin-top:10px;">
				<%= image_tag('logos/256/invierno.png', width: 150) %>
			    </div>
				<%end%>
			</div>
			<center>
			<% if !session[:admin].nil? %>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav col-md-10 pull-right">
					<li class="pull-right">
						<%= link_to log_out_path do %>
						<i class="fa fa-sign-out" aria-hidden="true"></i>
						<%end%>
					</li>
					<li class="pull-right">
						<%=link_to customers_path do %>Clientes<%end%>
					</li>
					
					<li class="pull-right">
						<li class="pull-right dropdown ">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administradores <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><%=link_to admins_path do %>Ver todos<%end%></li>
								<li><%=link_to new_admin_path do %>Nuevo Administrador<%end%></li>
							</ul>
						</li>
						<li class="pull-right dropdown ">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pedidos <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><%=link_to orders_path do %>Todos los pedidos<%end%></li>
								<li><%=link_to today_orders_path do %> Pedidos de hoy <%end%></li>
								<li><%=link_to  montly_orders_path do %> Pedidos del mes<%end%></li>
								<li><%=link_to inprocess_orders_path do %>Pedidos en proceso<%end%></li>
								<li><%=link_to in_send_orders_path do %>Pedidios en envio<%end%></li>
								<li><%=link_to finish_orders_path do %>Pedidios finalizados<%end%></li>
							</ul>
						</li>
						<li class="dropdown pull-right">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Productos <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="<%= products_path %>">Listado de productos</a></li>
								<li><%=link_to productos_no_publicados_path do %> Productos sin publicar <%end%> </li>
								<li><a href="<%= new_product_path %>">Nuevo Producto</a></li>
								<li><%=link_to import_list_path do %> Importación de lista <%end%> </li>
							</ul>
						</li>
						
					</ul>
					
					</div><!-- /.navbar-collapse -->
					</center>
					</div><!-- /.container-fluid -->
				</div>
				<%end%>
			</nav>

app/views/layout_parts/_head_menu.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-54614231-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-54614231-4');
</script>
<%= render partial: '/tienda/contacto' %>

<% if mobile_device? %>
<div class="cart">
	<a href="<%= lista_de_productos_path %>" style="color: #fff;">
		<center>
		<div class="cart-circle-btn">
			<span class="label label-warning" id="prodexp" style="margin-top:-10px;"><%= session[:product].size if !session[:product].nil? %></span> <br/>
			<i class="fa fa-shopping-cart" aria-hidden="true"></i>
			<div style="display:none;">: $<span id="pricexp"><%= (session[:price].to_f).round(2) if !session[:price].nil? %><%= "0" if session[:price].nil? %></span> MXN</div>
		</div>
	</div>
</a>
</div>
<%end%>
<div class="top-menu-2">
<div class="col-md-2">
	<center>
	<%= link_to root_path do %>
	<%= image_tag('logos/256/invierno.png', width: 180) %>
	<%end%>
	</center>
</div>
<div class="col-md-10 search-top">
	<center>
	<form action="<%= search_path %>" style="margin-top: 10px; z-index: 1">
		<div class="form-group">
			<div class="input-group input-group-md">
				<input type="text" name="search" class="form-control" placeholder="Buscar ... ">
				<span class="input-group-btn">
					<button type="submit" class="btn btn-success"><i class="fa fa-search" aria-hidden="true"></i></button>
				</span>
			</div>
		</div>
	</form>
	</center>
</div>
<!--<div class="col-md-2 social-top">
		<center>
		<h3 >
		<a>
				<i class="fa fa-facebook-official" aria-hidden="true"></i>
		</a>
		<a>
				<i class="fa fa-twitter-square" aria-hidden="true"></i>
		</a>
		<a>
		<i class="fa fa-youtube-square" aria-hidden="true"></i> </a>
		
		<a href="#" data-toggle="modal" data-target="#contactModal">
				<i class="fa fa-envelope" aria-hidden="true"></i>
		</a>
		</h3>
		</center>
</div>-->
</div>
<nav class="navbar navbar-inverse navbar-static-top">
<div class="container-fluid">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="search-mobile col-lg-12">
			<center>
			<form action="<%= search_path %>" style="margin-top: 10px; z-index: 1">
				<div class="form-group">
					<div class="input-group input-group-md">
						<input type="text" name="search" class="form-control" placeholder="Buscar ... ">
						<span class="input-group-btn">
							<button type="submit" class="btn btn-default"><i class="fa fa-search" aria-hidden="true"></i></button>
						</span>
					</div>
				</div>
			</form>
			</center>
		</div>
		<center>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1 ">
			<ul class="nav navbar-nav col-md-9 menu-change-colors">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categorías <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<%= render partial: '/layout_parts/cat_list' %>
					</ul>
				</li>
				<!--<li>
							<a href="#" >Ofertas y promociones</a>
				</li>-->
				<li>
					<%= link_to all_items_path do %>
					Todos los productos
					<%end%>
				</li>
			</ul>
			<div class="col-md-3">
				
			</div>
			<ul class="nav navbar-nav navbar-right col-md-3">
				<% unless mobile_device? %>
				<li ><a href="<%= lista_de_productos_path %>" style="color: #000;"><span class="label label-warning" id="prodexp"><%= session[:product].size if !session[:product].nil? %></span> Total <i class="fa fa-shopping-cart" aria-hidden="true"></i>: $<span id="pricexp"><%= (session[:price].to_f).round(2) if !session[:price].nil? %><%= "0" if session[:price].nil? %></span> MXN</a></li>
				<li><a href="<%=eliminar_items_del_carrito_path%>"><i class="fa fa-ban" aria-hidden="true"></i></a></li>
				<%end%>
			</ul>
			</div><!-- /.navbar-collapse -->
			</center>
			</div><!-- /.container-fluid -->
		</div>
	</nav>

app/views/layout_parts/_item_col.html.erb
<% if product.publicado %>
<div class="col-sm-6 col-md-4">
	<div class="thumbnail" style="height: auto !important; background: #fff; padding: 0px;">
		<div class="img-border">
			<%= link_to item_path(product.id) do -%>
			<% if img != nil %>
			<% if !product.oferta.nil? %>
			<%= image_tag 'oferta.png', width: '50%', style: 'position: absolute;' %>
			<%end%>
			<img src="<%= img.file.big%>" alt="img.file" width="100%">
			<%else%>
			<img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjQyIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDI0MiAyMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzEwMCV4MjAwCkNyZWF0ZWQgd2l0aCBIb2xkZXIuanMgMi42LjAuCkxlYXJuIG1vcmUgYXQgaHR0cDovL2hvbGRlcmpzLmNvbQooYykgMjAxMi0yMDE1IEl2YW4gTWFsb3BpbnNreSAtIGh0dHA6Ly9pbXNreS5jbwotLT48ZGVmcz48c3R5bGUgdHlwZT0idGV4dC9jc3MiPjwhW0NEQVRBWyNob2xkZXJfMTViMTJmOWMwNTYgdGV4dCB7IGZpbGw6I0FBQUFBQTtmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMnB0IH0gXV0+PC9zdHlsZT48L2RlZnM+PGcgaWQ9ImhvbGRlcl8xNWIxMmY5YzA1NiI+PHJlY3Qgd2lkdGg9IjI0MiIgaGVpZ2h0PSIyMDAiIGZpbGw9IiNFRUVFRUUiLz48Zz48dGV4dCB4PSI4OS44NTkzNzUiIHk9IjEwNS40Ij4yNDJ4MjAwPC90ZXh0PjwvZz48L2c+PC9zdmc+" alt="">
			<%end%>
			<%end%>
		</div>
		<div class="p-description">
			<div class="caption">
				<div class="col-md-9">
					<% if mobile_device? %>
					<h4><%= title.truncate(60, separator: '...') %> <% if !product.oferta.nil?%>  <i style="color:red;"></i> <%end%> </h4>
					<%else%>
					<h4><%= title.truncate(15, separator: '...') %> <% if !product.oferta.nil?%>  <i style="color:red;"></i> <%end%> </h4>
					<%end%>
					
				</div>
				<div class="col-md-3">
					<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal<%= product.id %>">
					<i class="fa fa-pagelines" aria-hidden="true"></i>
					</button>
				</div>
				<div class="col-lg-12 justify" >
					<p><%= descript.truncate(20, separator: '...') %></p>
				</div>
				<div class="col-lg-12" style="height: 50px;">
					<% if product.oferta.nil? %>
					<h4 style="text-align: right;">Precio: $<%=price%> MXN</h4>
					<%else%>
					<h4>
					<strike style="color: grey;">$<%=product.precio%></strike> -<%= product.oferta %>% <br/> 
					<p style="color: red;">desde $<%= product.precio_final %> MXN</p>
					</h4>
					<%end%>
				</div>
				<br/><br/>
				<div class="btn-group btn-group-justified">
					<%= link_to actualizar_carrito_path(product: product.id, price: product.precio_final, color: product.color1, cantidad: 1), class: "btn btn-warning btn-small ", remote: true do %>
					Agregar <i class="fa fa-cart-plus" aria-hidden="true"></i>
					<%end%>
					<%= link_to item_path(product.id), class: "btn btn-success btn-small " do -%>
					Detalles <i class="fa fa-list" aria-hidden="true"></i>
					<%end%>
				</div>
			</div>
		</div>
		</div>
	</div>
	<div class="modal fade" id="myModal<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel"><%= product.nombre %> (<%= product.nombre_cientifico %>)</h4>
				</div>
				<div class="modal-body">
					<div class="col-lg-12">
						<h4>Nuestra galeria</h4>
						<%product.image_products.each do |img| %>
						<div class="col-md-3">
							<%= image_tag(img.file.standar, width: '100%') %>
						</div>
						<%end%>
					</div>
					<br/><br/>
					<table class="table table-bordered">
						<caption>Necesidades</caption>
						<thead>
							<tr>
								<th>Luz</th>
								<th>Riego</th>
								<th>Tamaño</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><%= product.luz %></td>
								<td><%= product.riego %></td>
								<td><%= product.tamano %></td>
							</tr>
						</tbody>
					</table>
					<table class="table table-bordered">
						<caption>Datos Geográficos</caption>
						<thead>
							<tr>
								<th>Pais</th>
								<th>Región climática</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><%= product.pais_de_procedencia %></td>
								<td><%= product.region_climatica %></td>
							</tr>
						</tbody>
					</table>
					<table class="table table-bordered">
						<caption>Datos Científicos</caption>
						<thead>
							<tr>
								<th>Familia</th>
								<th>Orden</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><%= product.familia %></td>
								<td><%= product.orden %></td>
							</tr>
						</tbody>
					</table>
					<a href="<%= product.wikipedia_link %>" target="_blank" class="pull-right"><i>Ver mas en <i class="fa fa-wikipedia-w" aria-hidden="true"></i>ikipedia</i></a><br/><br/><br/><br/>
				</div>
				<div class="modal-footer">
					<div class="btn-group btn-group-justified">
						<%= link_to actualizar_carrito_path(product: product.id, price: price, color: product.color1, cantidad: 1), class: "btn btn-warning btn-small ", remote: true do %>
						Agregar <i class="fa fa-cart-plus" aria-hidden="true"></i>
						<%end%>
						<%= link_to item_path(product.id), class: "btn btn-success btn-small " do -%>
						Detalles <i class="fa fa-list" aria-hidden="true"></i>
						<%end%>
					</div>
				</div>
			</div>
		</div>
	</div>
	<%end%>

app/views/layout_parts/_search_shipment.html.erb
<form action="<%= buscar_pedido_path %>" style="margin-top: 10px; z-index: 1">
	<div class="form-group">
		<div class="input-group input-group-md">
			<input type="text" name="search" class="form-control" placeholder="Buscar pedido... ">
			<span class="input-group-btn">
				<button type="submit" class="btn btn-default"><i class="fa fa-truck" aria-hidden="true"></i></button>
			</span>
		</div>
	</div>
</form>